#############################################################################
# Makefile for building: libaversive_atmega2560.a
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  project/avr.pro
# Template: lib
# Command: /usr/bin/qmake-qt5 -Wall -o Makefile project/avr.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = avr-g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 $(DEFINES)
CXXFLAGS      = -std=c++11 -Wall -Wextra -mmcu=atmega2560 -O3 $(DEFINES)
INCPATH       = -I/usr/lib64/qt5/mkspecs/linux-g++-64 -Iproject -Iinclude/avr -I.
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt5
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/avr/

####### Files

SOURCES       = src/avr/aversive.cpp \
		src/avr/hardware/interrupts.cpp \
		src/avr/hardware/timer.cpp \
		src/avr/hardware/uart.cpp \
		src/avr/system/scheduler.cpp \
		src/common/geometry/quadrilateral_collision.cpp \
		src/common/geometry/point_collision.cpp \
		src/common/geometry/triangle_collision.cpp \
		src/common/geometry/aabb_collision.cpp \
		src/common/geometry/segment_collision.cpp \
		src/common/geometry/circle_collision.cpp \
		src/common/device/stream/formatted_stream_read.cpp \
		src/common/device/stream/formatted_stream_write.cpp \
		src/common/device/stream/stream.cpp \
		src/common/device/stream/binary_stream_read.cpp \
		src/common/device/stream/binary_stream_write.cpp \
		src/common/device/stream/internal_buffered_stream.cpp \
		src/common/math/random.cpp \
		src/common/filter/quadramp_filter.cpp \
		src/common/filter/pid_filter.cpp \
		src/common/filter/diff_filter.cpp 
OBJECTS       = build/avr/aversive.o \
		build/avr/interrupts.o \
		build/avr/timer.o \
		build/avr/uart.o \
		build/avr/scheduler.o \
		build/avr/quadrilateral_collision.o \
		build/avr/point_collision.o \
		build/avr/triangle_collision.o \
		build/avr/aabb_collision.o \
		build/avr/segment_collision.o \
		build/avr/circle_collision.o \
		build/avr/formatted_stream_read.o \
		build/avr/formatted_stream_write.o \
		build/avr/stream.o \
		build/avr/binary_stream_read.o \
		build/avr/binary_stream_write.o \
		build/avr/internal_buffered_stream.o \
		build/avr/random.o \
		build/avr/quadramp_filter.o \
		build/avr/pid_filter.o \
		build/avr/diff_filter.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		project/project/avr.pro \
		project/avr.pro
QMAKE_TARGET  = aversive_atmega2560
DESTDIR       = build/#avoid trailing-slash linebreak
TARGET        = libaversive_atmega2560.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build/$(TARGET) 

staticlib: build/$(TARGET)

build/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d build/ || mkdir -p build/
	-$(DEL_FILE) $(TARGET)
	avr-ar cqs ${TARGET} ${OBJECTS}
	-$(DEL_FILE) build/$(TARGET)
	-$(MOVE) $(TARGET) build/ 


Makefile: project/avr.pro /usr/lib64/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		project/avr.pro
	$(QMAKE) -Wall -o Makefile project/avr.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/shell-unix.conf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
project/avr.pro:
qmake: FORCE
	@$(QMAKE) -Wall -o Makefile project/avr.pro

qmake_all: FORCE

dist: 
	@test -d build/avr/aversive_atmega25601.0.0 || mkdir -p build/avr/aversive_atmega25601.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/avr/aversive_atmega25601.0.0/ && (cd `dirname build/avr/aversive_atmega25601.0.0` && $(TAR) aversive_atmega25601.0.0.tar aversive_atmega25601.0.0 && $(COMPRESS) aversive_atmega25601.0.0.tar) && $(MOVE) `dirname build/avr/aversive_atmega25601.0.0`/aversive_atmega25601.0.0.tar.gz . && $(DEL_FILE) -r build/avr/aversive_atmega25601.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) build/$(TARGET) 
	-$(DEL_FILE) Makefile


compiler_clean: 

####### Compile

build/avr/aversive.o: src/avr/aversive.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/aversive.o src/avr/aversive.cpp

build/avr/interrupts.o: src/avr/hardware/interrupts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/interrupts.o src/avr/hardware/interrupts.cpp

build/avr/timer.o: src/avr/hardware/timer.cpp src/avr/hardware/interrupt_bind.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/timer.o src/avr/hardware/timer.cpp

build/avr/uart.o: src/avr/hardware/uart.cpp src/avr/hardware/interrupt_bind.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/uart.o src/avr/hardware/uart.cpp

build/avr/scheduler.o: src/avr/system/scheduler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/scheduler.o src/avr/system/scheduler.cpp

build/avr/quadrilateral_collision.o: src/common/geometry/quadrilateral_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/quadrilateral_collision.o src/common/geometry/quadrilateral_collision.cpp

build/avr/point_collision.o: src/common/geometry/point_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/point_collision.o src/common/geometry/point_collision.cpp

build/avr/triangle_collision.o: src/common/geometry/triangle_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/triangle_collision.o src/common/geometry/triangle_collision.cpp

build/avr/aabb_collision.o: src/common/geometry/aabb_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/aabb_collision.o src/common/geometry/aabb_collision.cpp

build/avr/segment_collision.o: src/common/geometry/segment_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/segment_collision.o src/common/geometry/segment_collision.cpp

build/avr/circle_collision.o: src/common/geometry/circle_collision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/circle_collision.o src/common/geometry/circle_collision.cpp

build/avr/formatted_stream_read.o: src/common/device/stream/formatted_stream_read.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/formatted_stream_read.o src/common/device/stream/formatted_stream_read.cpp

build/avr/formatted_stream_write.o: src/common/device/stream/formatted_stream_write.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/formatted_stream_write.o src/common/device/stream/formatted_stream_write.cpp

build/avr/stream.o: src/common/device/stream/stream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/stream.o src/common/device/stream/stream.cpp

build/avr/binary_stream_read.o: src/common/device/stream/binary_stream_read.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/binary_stream_read.o src/common/device/stream/binary_stream_read.cpp

build/avr/binary_stream_write.o: src/common/device/stream/binary_stream_write.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/binary_stream_write.o src/common/device/stream/binary_stream_write.cpp

build/avr/internal_buffered_stream.o: src/common/device/stream/internal_buffered_stream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/internal_buffered_stream.o src/common/device/stream/internal_buffered_stream.cpp

build/avr/random.o: src/common/math/random.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/random.o src/common/math/random.cpp

build/avr/quadramp_filter.o: src/common/filter/quadramp_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/quadramp_filter.o src/common/filter/quadramp_filter.cpp

build/avr/pid_filter.o: src/common/filter/pid_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/pid_filter.o src/common/filter/pid_filter.cpp

build/avr/diff_filter.o: src/common/filter/diff_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/avr/diff_filter.o src/common/filter/diff_filter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

